version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/client"
    schedule:
      interval: "daily"
    groups:
      all:
        patterns: "*"
    target-branch: "refactor-cli"


  - package-ecosystem: "gradle"
    directory: "/command"
    schedule:
      interval: "daily"
    groups:
      all:
        patterns: "*"
    target-branch: "refactor-cli"

  - package-ecosystem: "gradle"
    directory: "/common"
    schedule:
      interval: "daily"
    groups:
      all:
        patterns: "*"
    target-branch: "refactor-cli"


  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    groups:
      all:
        patterns: "*"
    target-branch: "refactor-cli"
