name: Build

on:
  push:
    branches: [unit_testing_with_github_actions]
#  pull_request:
#    branches: [unit_testing_with_github_actions]

jobs:
  gradle:
    env:
      java_version: 17
    strategy:
      matrix:
          # the following defines different platforms to target for different actions
          # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK ${{ env.java_version }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "${{ env.java_version }}"
          cache: 'gradle'

#      - name: Build
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: build
#          gradle-version: 8.0.2

      - name: Build Code
        run: gradlew build --no-daemon

      - name: Run Tests
        run: gradlew test --no-daemon