#################################################################
# Prototype to demonstrate running a build with tests
#################################################################

name: Build and Run Tests

on:
  push:
    branches: [unit_testing_with_github_actions]

jobs:
  gradle:
    env:
      java_version: 17
    strategy:
      matrix:
          # the following defines different platforms to target for different actions
          # os: [ubuntu-latest, macos-latest, windows-latest]
          # ubuntu-latest,
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: unit_testing_with_github_actions
      - name: Set up JDK ${{ env.java_version }}
        uses: actions/setup-java@v3
        with:
          java-version: '${{ env.java_version }}'
          distribution: 'temurin'

      # GitHub Policy: up to 10GB in caches w/removal after 7 days of no access.
      # The following caches the gradle instance for later use
      - name: Cache Gradle packages
        uses: actions/cache@v3
        env:
          cache-name: cache-gradle
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/gradle-wrapper.properties') }} # key for this gradle instance in cache
          restore-keys: | # keys to use in case the provided key doesn't hit the cache
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Requires gradle-wrapper.jar checked into code
      # Validates that if the gradle-wrapper.jar is checked in the hashes match
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          # builds the project and runs test
          arguments: test
          gradle-version: 8.0.2
