#################################################################
# Working example to validate different steps
#################################################################

# Testing with tag

name: example-actions-runners

on:
  push:
    # only run on branch "unit_testing_with_github_actions"
    branches: [unit_testing_with_github_actions]

jobs:
  echo_on_runners:
    env:
      java_version: 17
    strategy:
      matrix:
        #   GitHub-hosted runners as of 5/5/23
        #   windows-latest = windows-2022
        #   ubuntu-latest = ubuntu-22.04
        #   macos-latest = macos-12
        #
        #   Additional details at https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
        os: [windows-latest, windows-2019, ubuntu-18.04, macos-13, macos-12, macos-11]
        # os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: noop
        run: echo noop

