#################################################################
# Prototype to demonstrate running a build release
#################################################################

name: Build and Run Tests

on:
  push:
    branches: [unit_testing_with_github_actions]

jobs:
  gradle:
    env:
      java_version: 17
    strategy:
      matrix:
          # the following defines different platforms to target for different actions
          # os: [ubuntu-latest, macos-latest, windows-latest]
          # ubuntu-latest,
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: unit_testing_with_github_actions
      - name: Set up JDK ${{ env.java_version }}
        uses: actions/setup-java@v3
        with:
          java-version: '${{ env.java_version }}'
          distribution: oracle
          cache: gradle

      - name: Execute gradle build
        run: ./gradlew bootJar
