#################################################################
# Prototype to demonstrate running a build with tests
#################################################################

name: Build and Run Tests

on:
  push:
    # run this when a tag with "test" as a prefix is created
    tags:
      - 'test.*'
    # only run on branch "unit_testing_with_github_actions"
    branches: [unit_testing_with_github_actions]

    #  pull_request:
    #    branches: [unit_testing_with_github_actions]

jobs:
  gradle:
    env:
      java_version: 17
    strategy:
      matrix:
          # the following defines different platforms to target for different actions
          # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ env.java_version }}
        uses: actions/setup-java@v3
        with:
          java-version: '${{ env.java_version }}'
          distribution: 'temurin'

      # GitHub Policy: up to 10GB in caches w/removal after 7 days of no access.
      - name: Cache Gradle packages
        uses: actions/cache@v3
        env:
          cache-name: cache-gradle
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Requires gradle-wrapper.jar checked into code
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
          gradle-version: 8.0.2
