#################################################################
# Working example to validate different steps
#################################################################

# Testing with tag

name: working-example

on:
  push:
    # run this when a tag with "test" as a prefix is created
    tags:
      - test.*
    # only run on branch "unit_testing_with_github_actions"
    # branches: [unit_testing_with_github_actions]

    #  pull_request:
    #    branches: [unit_testing_with_github_actions]

jobs:
  test_action:
    env:
      java_version: 17
    strategy:
      matrix:
          # the following defines different platforms to target for different actions
          # os: [ubuntu-latest, macos-latest, windows-latest]
          # ubuntu-latest,
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: noop
        run: echo noop

